import Head from "next/head";
import { useEffect, useState } from "react";
import { Box, Grid } from "@chakra-ui/react";

import Card from "../../components/Card/Card";

export default function Cats() {
  const [cats, setCats] = useState([]);

  const fetchCats = async () => {
    const res = await fetch("/api/cats");
    const data = await res.json();

    setCats(data);
  };

  useEffect(() => {
    fetchCats();
  }, []);

  return (
    <>
      <Head>
        <title>Cats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box p={2} w={"80%"} m="auto" mt={5}>
        <Grid
          p={1}
          gap={5}
          w={"70%"}
          margin="auto"
          mt={5}
          templateColumns="repeat(auto-fit,minmax(250px,2fr))"
        >
          {cats.map((cat) => (
            <Card
              key={cat.id}
              image={cat.image}
              name={cat.name}
              phone={cat.phone}
              email={cat.email}
              id={cat.id}
            />
          ))}
        </Grid>
      </Box>
    </>
  );
}
